import React from "react";
import type { Metadata } from "next";
import Script from "next/script";

// Here we are using the inline Script Id (it contains an id and the script to run)
// Here strategy="afterInteractive" is the default property for more info see doc

export default function About() {
  return <div>
    <Script id="alert-script" strategy="afterInteractive" >{`alert("hiiii")`}</Script>
    This is About
    </div>;
}

export const metadata: Metadata = {
  title: "about",
  description: "Generated by create next app",
};
