import type { Metadata } from "next";
import React from "react";
import Image from "next/image";

// Here if i want to use the external image i need to config the next.config.ts

export default function Contact() {
  return (
    <div>
      <Image
        src={
          "https://media.istockphoto.com/id/1452771551/vector/contact-us-button-with-cursor-pointer-click-vector-web-button.jpg?s=612x612&w=0&k=20&c=IGWQ-VhsNAnZyKnuWhggHhpozUiuFRq5jd-rJ7-KqIc="
        }
        width={500}
        height={500}
        alt="contact"
      />
    </div>
  );
}

export const metadata: Metadata = {
  // if we remove the title we don't need to import metanode type
  title: "This is contact",
  description: "Generated by create next app",
};
